Test 32bit uuid before testing for dcgm

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5189,6 +5189,83 @@ if test $HAVE_WORKING_LIBUUID = no -a ! -f /proc/sys/kernel/random/uuid; then
    exit 1
 fi
 
+if test $HAVE_32BIT = yes -a $HAVE_WORKING_LIBUUID = yes; then
+   CFLAGS_OLD=$CFLAGS
+   CFLAGS="-m32 $CFLAGS"
+   { $as_echo "$as_me:${as_lineno-$LINENO}: checking for library containing uuid_clear" >&5
+$as_echo_n "checking for library containing uuid_clear... " >&6; }
+if ${ac_cv_search_uuid_clear+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char uuid_clear ();
+int
+main ()
+{
+return uuid_clear ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' uuid; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_search_uuid_clear=$ac_res
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext
+  if ${ac_cv_search_uuid_clear+:} false; then :
+  break
+fi
+done
+if ${ac_cv_search_uuid_clear+:} false; then :
+
+else
+  ac_cv_search_uuid_clear=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_search_uuid_clear" >&5
+$as_echo "$ac_cv_search_uuid_clear" >&6; }
+ac_res=$ac_cv_search_uuid_clear
+if test "$ac_res" != no; then :
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+  HAVE_WORKING_LIBUUID_32=yes
+else
+  HAVE_WORKING_LIBUUID_32=no
+fi
+
+   CFLAGS=$CFLAGS_OLD
+   if test $HAVE_WORKING_LIBUUID_32 = no; then
+      echo
+      echo "======================================================="
+      echo "Unable to install XALT without a 32 version of the"
+      echo "uuid library"
+      echo ""
+      echo "Your system has the 64 bit version of libuuid but not"
+      echo "the 32 bit version."
+      echo "======================================================="
+      echo
+      rm -f makefile
+      exit 1
+   fi
+fi
+
 
 HAVE_DCGM=no
 if test $XALT_GPU_TRACKING = yes; then
@@ -5381,83 +5458,6 @@ if test "$USE_CONTRIB_ARGPARSE" = yes; then
       export PYTHONPATH=$ac_confdir/contrib/argparse
    else
       export PYTHONPATH=$ac_confdir/contrib/argparse:$PYTHONPATH
-   fi
-fi
-
-if test $HAVE_32BIT = yes -a $HAVE_WORKING_LIBUUID = yes; then
-   CFLAGS_OLD=$CFLAGS
-   CFLAGS="-m32 $CFLAGS"
-   { $as_echo "$as_me:${as_lineno-$LINENO}: checking for library containing uuid_clear" >&5
-$as_echo_n "checking for library containing uuid_clear... " >&6; }
-if ${ac_cv_search_uuid_clear+:} false; then :
-  $as_echo_n "(cached) " >&6
-else
-  ac_func_search_save_LIBS=$LIBS
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char uuid_clear ();
-int
-main ()
-{
-return uuid_clear ();
-  ;
-  return 0;
-}
-_ACEOF
-for ac_lib in '' uuid; do
-  if test -z "$ac_lib"; then
-    ac_res="none required"
-  else
-    ac_res=-l$ac_lib
-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
-  fi
-  if ac_fn_c_try_link "$LINENO"; then :
-  ac_cv_search_uuid_clear=$ac_res
-fi
-rm -f core conftest.err conftest.$ac_objext \
-    conftest$ac_exeext
-  if ${ac_cv_search_uuid_clear+:} false; then :
-  break
-fi
-done
-if ${ac_cv_search_uuid_clear+:} false; then :
-
-else
-  ac_cv_search_uuid_clear=no
-fi
-rm conftest.$ac_ext
-LIBS=$ac_func_search_save_LIBS
-fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_search_uuid_clear" >&5
-$as_echo "$ac_cv_search_uuid_clear" >&6; }
-ac_res=$ac_cv_search_uuid_clear
-if test "$ac_res" != no; then :
-  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
-  HAVE_WORKING_LIBUUID_32=yes
-else
-  HAVE_WORKING_LIBUUID_32=no
-fi
-
-   CFLAGS=$CFLAGS_OLD
-   if test $HAVE_WORKING_LIBUUID_32 = no; then
-      echo
-      echo "======================================================="
-      echo "Unable to install XALT without a 32 version of the"
-      echo "uuid library"
-      echo ""
-      echo "Your system has the 64 bit version of libuuid but not"
-      echo "the 32 bit version."
-      echo "======================================================="
-      echo
-      rm -f makefile
-      exit 1
    fi
 fi
 
