new configure.ac?

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1792,7 +1792,7 @@ $as_echo "ACCEPT_LIST=$with_acceptList" >&6; }
 _ACEOF
 
 else
-  withval="$ac_confdir/accept.default.txt"
+  withval="accept.default.txt"
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: ACCEPT_LIST=$withval" >&5
 $as_echo "ACCEPT_LIST=$withval" >&6; }
     ACCEPT_LIST="$withval"
@@ -1814,7 +1814,7 @@ $as_echo "IGNORE_LIST=$with_ignoreList" >&6; }
 _ACEOF
 
 else
-  withval="$ac_confdir/ignore.default.txt"
+  withval="ignore.default.txt"
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: IGNORE_LIST=$withval" >&5
 $as_echo "IGNORE_LIST=$withval" >&6; }
     IGNORE_LIST="$withval"
@@ -1836,7 +1836,7 @@ $as_echo "HOSTNAME_LIST=$with_hostnameList" >&6; }
 _ACEOF
 
 else
-  withval="$ac_confdir/hostname.default.txt"
+  withval="hostname.default.txt"
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: HOSTNAME_LIST=$withval" >&5
 $as_echo "HOSTNAME_LIST=$withval" >&6; }
     HOSTNAME_LIST="$withval"
@@ -2687,20 +2687,20 @@ $as_echo "no" >&6; }
 if test "$HAVE_PYMOD_MYSQLDB" = no; then
    echo "unable to install XALT without the python module: MySQLdb"
    echo "To install it do: pip install MySQL-python"
-fi
-
-
-if test "$HAVE_PYMOD_PSUTIL" = yes; then
-   echo "You must have the python module: psutil in order to use xalt.
    exit 1
 fi
 
 
+if test "$HAVE_PYMOD_PSUTIL" = no; then
+   echo "unable to install XALT without the python module: psutil"
+   echo "To install it do: pip install psutil"
+   exit 1
+fi
 
 
 printf "Use contrib argparse"
 USE_CONTRIB_ARGPARSE=no
-versionStr=$($PATH_TO_PYTHON --version 2>&1 | head -1)
+versionStr=$(python --version 2>&1 | head -1)
 major_version=`expr "$versionStr" : 'Python \+\([0-9]\+\)\.'`
 minor_version=`expr "$versionStr" : 'Python \+[0-9]\+\.\([0-9]\+\)'`
 version=`expr $major_version \* 100000 + $minor_version`
@@ -2711,6 +2711,7 @@ fi
 echo "... $USE_CONTRIB_ARGPARSE"
 
 $PATH_TO_PYTHON $ac_confdir/src/build_xalt_regex.py --accept $ACCEPT_LIST --ignore $IGNORE_LIST --hostname $HOSTNAME_LIST --input $ac_confdir/src/xalt_regex.template --output $ac_confdir/src/xalt_regex.h
+
 
 ac_config_files="$ac_config_files makefile:Makefile.in"
 
