Adding support for building XALT w/o mysql

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -659,7 +659,7 @@ SYSHOST_CONFIG
 MYSQL_STATIC
 SYSLOG_MSG_SZ
 SYSTEM_PATH
-PYMOD_MYSQLDB
+MYSQLDB
 XALT_CONFIG_PY
 ETC_DIR
 XALT_FILE_PREFIX
@@ -691,7 +691,6 @@ infodir
 docdir
 oldincludedir
 includedir
-runstatedir
 localstatedir
 sharedstatedir
 sysconfdir
@@ -718,7 +717,7 @@ with_transmission
 with_xaltFilePrefix
 with_etcDir
 with_config
-with_pymodMySQL
+with_MySQL
 with_systemPath
 with_syslogMsgSz
 with_mysqlStatic
@@ -771,7 +770,6 @@ datadir='${datarootdir}'
 sysconfdir='${prefix}/etc'
 sharedstatedir='${prefix}/com'
 localstatedir='${prefix}/var'
-runstatedir='${localstatedir}/run'
 includedir='${prefix}/include'
 oldincludedir='/usr/include'
 docdir='${datarootdir}/doc/${PACKAGE}'
@@ -1024,15 +1022,6 @@ do
   | -silent | --silent | --silen | --sile | --sil)
     silent=yes ;;
 
-  -runstatedir | --runstatedir | --runstatedi | --runstated \
-  | --runstate | --runstat | --runsta | --runst | --runs \
-  | --run | --ru | --r)
-    ac_prev=runstatedir ;;
-  -runstatedir=* | --runstatedir=* | --runstatedi=* | --runstated=* \
-  | --runstate=* | --runstat=* | --runsta=* | --runst=* | --runs=* \
-  | --run=* | --ru=* | --r=*)
-    runstatedir=$ac_optarg ;;
-
   -sbindir | --sbindir | --sbindi | --sbind | --sbin | --sbi | --sb)
     ac_prev=sbindir ;;
   -sbindir=* | --sbindir=* | --sbindi=* | --sbind=* | --sbin=* \
@@ -1170,7 +1159,7 @@ fi
 for ac_var in	exec_prefix prefix bindir sbindir libexecdir datarootdir \
 		datadir sysconfdir sharedstatedir localstatedir includedir \
 		oldincludedir docdir infodir htmldir dvidir pdfdir psdir \
-		libdir localedir mandir runstatedir
+		libdir localedir mandir
 do
   eval ac_val=\$$ac_var
   # Remove trailing slashes.
@@ -1323,7 +1312,6 @@ Fine tuning of the installation directories:
   --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
   --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
   --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
-  --runstatedir=DIR       modifiable per-process data [LOCALSTATEDIR/run]
   --libdir=DIR            object code libraries [EPREFIX/lib]
   --includedir=DIR        C header files [PREFIX/include]
   --oldincludedir=DIR     C header files for non-gcc [/usr/include]
@@ -1357,8 +1345,7 @@ Optional Packages:
                           found [[.]]
   --with-config=ans       A python file defining the accept, ignore, hostname
                           pattern lists [[NO DEFAULT]]
-  --with-pymodMySQL=ans   Require the python MySQLdb module to build XALT
-                          [[yes]]
+  --with-MySQL=ans        Require MySQL and the MySQL-python module [[yes]]
   --with-systemPath=ans
   --with-syslogMsgSz=ans
   --with-mysqlStatic=ans  Require that libmysqlclient be linked in statically
@@ -3004,22 +2991,22 @@ fi
 
 
 
-# Check whether --with-pymodMySQL was given.
-if test "${with_pymodMySQL+set}" = set; then :
-  withval=$with_pymodMySQL; PYMOD_MYSQLDB="$withval"
-    { $as_echo "$as_me:${as_lineno-$LINENO}: result: PYMOD_MYSQLDB=$with_pymodMySQL" >&5
-$as_echo "PYMOD_MYSQLDB=$with_pymodMySQL" >&6; }
+# Check whether --with-MySQL was given.
+if test "${with_MySQL+set}" = set; then :
+  withval=$with_MySQL; MYSQLDB="$withval"
+    { $as_echo "$as_me:${as_lineno-$LINENO}: result: MYSQLDB=$with_pymodMySQL" >&5
+$as_echo "MYSQLDB=$with_pymodMySQL" >&6; }
     cat >>confdefs.h <<_ACEOF
-#define PYMOD_MYSQLDB "$with_pymodMySQL"
+#define MYSQLDB "$with_MySQL"
 _ACEOF
 
 else
   withval="yes"
-    { $as_echo "$as_me:${as_lineno-$LINENO}: result: PYMOD_MYSQLDB=$withval" >&5
-$as_echo "PYMOD_MYSQLDB=$withval" >&6; }
-    PYMOD_MYSQLDB="$withval"
+    { $as_echo "$as_me:${as_lineno-$LINENO}: result: MYSQLDB=$withval" >&5
+$as_echo "MYSQLDB=$withval" >&6; }
+    MYSQLDB="$withval"
     cat >>confdefs.h <<_ACEOF
-#define PYMOD_MYSQLDB "$withval"
+#define MYSQLDB "$withval"
 _ACEOF
 
 fi
@@ -4618,31 +4605,34 @@ if ! test -f $XALT_CONFIG_PY; then
    exit 1
 fi
 
-if test "$MYSQL_CONFIG" = UNKNOWN; then
-   echo
-   echo "======================================================="
-   echo "Unable to install XALT without the program mysql_config"
-   echo "This program is used to find the MySQL installation"
-   echo "See the manual for details"
-   echo "======================================================="
-   exit 1
-fi
 
-if test "$PYMOD_MYSQLDB" != no -a "$HAVE_PYMOD_MYSQLDB" = no; then
+if test "$MYSQLDB" = yes; then
+   if "$HAVE_PYMOD_MYSQLDB" = no; then
+      echo
+      echo "======================================================="
+      echo "Unable to install XALT without the python module: MySQLdb"
+      echo "To install it do: pip install MySQL-python"
+      echo "======================================================="
+      exit 1
+   fi
+   if test "$MYSQL_CONFIG" = UNKNOWN; then
+      echo
+      echo "======================================================="
+      echo "Unable to install XALT without the program mysql_config"
+      echo "This program is used to find the MySQL installation"
+      echo "See the manual for details"
+      echo "======================================================="
+      exit 1
+   fi
+else
+   MYSQL_CONFIG=UNKNOWN
    echo
    echo "======================================================="
-   echo "Unable to install XALT without the python module: MySQLdb"
-   echo "To install it do: pip install MySQL-python"
-   echo "======================================================="
-   exit 1
-fi
-
-if test "$HAVE_PYMOD_MYSQLDB" = no; then
-   echo
-   echo "======================================================="
-   echo "XALT only requires the MySQL-python module when analyzing"
-   echo "data.  Make sure that you install MySQL-python module"
-   echo "where every you are analyzing the XALT data"
+   echo "XALT only requires MySQL libraries and MySQL-python module
+   echo "when loading and analyzing the XALT Data. Make sure"
+   echo "that you install the MySQL libraries, Devel packages
+   echo "and MySQL-python module where every you are analyzing
+   echo "the XALT data."
    echo "======================================================="
 fi
 
@@ -4658,9 +4648,6 @@ if test "$SYSHOST_CONFIG" = no; then
    echo "======================================================="
    exit 1
 fi
-
-
-
 
 printf "Use contrib argparse"
 USE_CONTRIB_ARGPARSE=no
