Make contrib/TACC/build_default_user_2_account_str.in be python 2/3 compliant

diff --git a/contrib/TACC/build_default_user_2_account_str.in b/contrib/TACC/build_default_user_2_account_str.in
--- a/contrib/TACC/build_default_user_2_account_str.in
+++ b/contrib/TACC/build_default_user_2_account_str.in
@@ -1,5 +1,21 @@
-#!/usr/bin/env python3
+#!/bin/sh
 # -*- python -*-
+
+################################################################################
+# This file is python 2/3 bilingual. 
+# The line """:" starts a comment in python and is a no-op in shell.
+""":"
+# Shell code to find and run a suitable python interpreter.
+for cmd in python3 python python2; do
+   command -v > /dev/null $cmd && exec $cmd $0 "$@"
+done
+
+echo "Error: Could not find a valid python interpreter --> exiting!" >&2
+exit 2
+":""" # this line ends the python comment and is a no-op in shell.
+################################################################################
+
+# Git Version: @git@
 
 ########################################################################
 # This a TACC specify tool to get the default accounting string for
