Safer way for the function tracking linking.

diff --git a/src/ld.in b/src/ld.in
--- a/src/ld.in
+++ b/src/ld.in
@@ -152,47 +152,38 @@ else
   OBJ=""
 fi
 
-# Save compiler generated tmp files (via hard link)
+( # start intentional fail link for function tracking
+$MY_CMD `$MY_PYTHON $XALT_LIBEXEC_DIR/xalt_strip_linklib.py \
+  "${argA[@]}"` --unresolved-symbols=report-all -o /dev/null > $FUNCRAW 2>&1
+) &
 
-$MKDIR -p $WRKDIR/obj
-for sf in "${argA[@]}"
-do
-  if [[ -e $sf ]]; then
-    if [[ $sf == "/tmp/"* ]]; then
-      cp -al $sf $WRKDIR/obj/
-    fi
-  fi
-done
-
-tracing_msg $MY_CMD "${argA[@]}"
-
-$MY_CMD "${argA[@]}" $OBJ -t > $LINKLINE_OUT 
-status=$?
-
-# start asynchronous subshell while the 'main' can return to user
-( 
 #Save python state
 py_path_xalt=$PYTHONPATH
 py_home_xalt=$PYTHONHOME
 export PYTHONPATH=$py_path_orig
 [ -n "$py_home_orig" ] && export PYTHONHOME=$py_home_orig
 
-$MY_CMD `$MY_PYTHON $XALT_LIBEXEC_DIR/xalt_strip_linklib.py $WRKDIR \
-  "${argA[@]}"` --unresolved-symbols=report-all -o /dev/null > $FUNCRAW 2>&1
+tracing_msg $MY_CMD "${argA[@]}"
 
-touch $FUNCLIST #-- Make sure file exist to avoid exception in $GEN_LINKDATA
-cat $FUNCRAW | while read line 
-do
-        getfunc=$(echo $line | awk '{print $5}' | sed s/.//1)
-        echo $getfunc | awk -F\' '{print $1}' | sed '/^$/d' >> $FUNCLIST
-done
+$MY_CMD "${argA[@]}" $OBJ -t > $LINKLINE_OUT 
+status=$?
 
-tracing_msg XALT_FUNCTION_TRACKING `cat $FUNCLIST`
+wait #-- wait for subshell to finish
 
 #Return python state
 export PYTHONPATH=$py_path_xalt
 unset  PYTHONHOME
 [ -n "$py_home_xalt" ] && export PYTHONHOME=$py_home_xalt
+
+( # start asynchronous subshell while the 'main' can return to user
+touch $FUNCLIST #-- Make sure file exist to avoid exception in $GEN_LINKDATA
+
+cat $FUNCRAW | while read line 
+do
+        getfunc=$(echo $line | awk '{print $5}' | sed s/.//1)
+        echo $getfunc | awk -F\' '{print $1}' | sed '/^$/d' >> $FUNCLIST
+done
+tracing_msg XALT_FUNCTION_TRACKING `cat $FUNCLIST`
 
 if [ -n "$USER_TRACE" ]; then
   $CAT $LINKLINE_OUT | $GREP -v $ARGOBJ
@@ -200,7 +191,9 @@ fi
 
 tracing_msg XALT_TRANSMISSION_STYLE $XALT_TRANSMISSION_STYLE
 
-$MY_PYTHON "$GEN_LINKDATA" "$UUID" "$status" "`pwd`" "$SYSHOST" "$EXEC" "$ARGOBJ" "$EPOCH" "$COMPILER" "$FUNCLIST" "$LINKLINE_OUT" "$RESULT"
+STARTTIME=$(date +%s)
+$MY_PYTHON "$GEN_LINKDATA" "$UUID" "$status" "`pwd`" "$SYSHOST" "$EXEC" \
+  "$ARGOBJ" "$EPOCH" "$COMPILER" "$FUNCLIST" "$LINKLINE_OUT" "$RESULT"
 
 if [ "$?" = 0 -a -n "${XALT_LD_DEBUG:-}" ]; then
    builtin echo ""                       >> $RESULT
@@ -210,9 +203,9 @@ if [ "$?" = 0 -a -n "${XALT_LD_DEBUG:-}" ]; then
 
    $CAT  $LINKLINE >> $RESULT
 fi
+ENDTIME=$(date +%s)
 
 $RM -rf $WRKDIR
-) &
-# end subshell
+) & # end subshell
 
 exit $status
